{ stdenv, fetchurl, udisks, bash }:

stdenv.mkDerivation rec {
 
  name = "bashmount-1.6.2";
  src = fetchurl {
    # url = http://downloads.sourceforge.net/bashmount/bashmount-1.6.2.tar.gz;
    url = "mirror://sourceforge/bashmount/${name}.tar.gz";
    sha256 = "10e5c8f9065e2410c5018d74a3f8cf7f30668fafa30d9ed82ff04cd64a0f7309";
  };

  buildInputs = [ udisks bash ];
  inherit udisks;
  inherit bash;
 
  buildPhase = ''
    mv bashmount bashmount.orig
    substituteInPlace ./bashmount.orig \
      --replace /etc/bashmount.conf $out/etc/bashmount.conf

    cat > bashmount <<EOF
    #!$bash/bin/bash
    #### Autogenerated header for nix
    # include udisks in path
    export PATH=$udisks/bin:\$PATH
    #### End autogenerated header
    EOF
    cat bashmount.orig >> bashmount
    chmod a+x bashmount
  '';  

  installPhase = ''
    install -d $out/bin
    install -d $out/etc
    install bashmount $out/bin
    install bashmount.conf $out/etc
  ''; 
}
